# Generated by Django 3.1.5 on 2021-01-30 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161129_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='trello_token',
        ),
        migrations.RemoveField(
            model_name='board',
            name='user',
        ),
    ]
