# Generated by Django 3.1.5 on 2021-01-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210130_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='trello_token',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
